sudo: false

language: node_js

node_js:
  - 8
  - 7
  - 6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

install:
  - export CXX="g++-4.8"
  - yarn
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - node ./internals/scripts/generate-templates-for-linting
  - yarn dist

notifications:
  email:
    on_failure: change

after_success: 'yarn run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
